In [4]:
import pandas as pd  # this is the standard alias


PATH = 'D://py_projects/ML/ML Demo/data/'
df = pd.read_csv(f"{PATH}house_pre_train.csv", index_col='Id')
df.head() # show the first five the rows of the data

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>MSSubClass</th>
      <th>MSZoning</th>
      <th>LotFrontage</th>
      <th>LotArea</th>
      <th>Street</th>
      <th>Alley</th>
      <th>LotShape</th>
      <th>LandContour</th>
      <th>Utilities</th>
      <th>LotConfig</th>
      <th>...</th>
      <th>PoolArea</th>
      <th>PoolQC</th>
      <th>Fence</th>
      <th>MiscFeature</th>
      <th>MiscVal</th>
      <th>MoSold</th>
      <th>YrSold</th>
      <th>SaleType</th>
      <th>SaleCondition</th>
      <th>SalePrice</th>
    </tr>
    <tr>
      <th>Id</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>60</td>
      <td>RL</td>
      <td>65.0</td>
      <td>8450</td>
      <td>Pave</td>
      <td>NaN</td>
      <td>Reg</td>
      <td>Lvl</td>
      <td>AllPub</td>
      <td>Inside</td>
      <td>...</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>2</td>
      <td>2008</td>
      <td>WD</td>
      <td>Normal</td>
      <td>208500</td>
    </tr>
    <tr>
      <th>2</th>
      <td>20</td>
      <td>RL</td>
      <td>80.0</td>
      <td>9600</td>
      <td>Pave</td>
      <td>NaN</td>
      <td>Reg</td>
      <td>Lvl</td>
      <td>AllPub</td>
      <td>FR2</td>
      <td>...</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>5</td>
      <td>2007</td>
      <td>WD</td>
      <td>Normal</td>
      <td>181500</td>
    </tr>
    <tr>
      <th>3</th>
      <td>60</td>
      <td>RL</td>
      <td>68.0</td>
      <td>11250</td>
      <td>Pave</td>
      <td>NaN</td>
      <td>IR1</td>
      <td>Lvl</td>
      <td>AllPub</td>
      <td>Inside</td>
      <td>...</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>9</td>
      <td>2008</td>
      <td>WD</td>
      <td>Normal</td>
      <td>223500</td>
    </tr>
    <tr>
      <th>4</th>
      <td>70</td>
      <td>RL</td>
      <td>60.0</td>
      <td>9550</td>
      <td>Pave</td>
      <td>NaN</td>
      <td>IR1</td>
      <td>Lvl</td>
      <td>AllPub</td>
      <td>Corner</td>
      <td>...</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>2</td>
      <td>2006</td>
      <td>WD</td>
      <td>Abnorml</td>
      <td>140000</td>
    </tr>
    <tr>
      <th>5</th>
      <td>60</td>
      <td>RL</td>
      <td>84.0</td>
      <td>14260</td>
      <td>Pave</td>
      <td>NaN</td>
      <td>IR1</td>
      <td>Lvl</td>
      <td>AllPub</td>
      <td>FR2</td>
      <td>...</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>12</td>
      <td>2008</td>
      <td>WD</td>
      <td>Normal</td>
      <td>250000</td>
    </tr>
  </tbody>
</table>
<p>5 rows Ã— 80 columns</p>
</div>

In [9]:

b = [[656.96,7100,3021.76,2240,3647.99,152,1584.2,4780,2012.98,2909,1056,5682.04,5915.09,1865,621,1406,3889.82,652.2,1283,2293.09,4814,5798.37,2511,14862,1739,2079,530.12,481.6,1250.16,731,1430,1487.11,568.74,220.97,194,14095.37,1795,574.87,2339.23,3743,372,3842,9139.66,9878,1202,1336.66,4599,17750.02,1216,5686.31,508.6,5855,696,2204,910,1091,665,1225.59,668,12170,126.5,1798,1445,2147,681.14,2687.78,951.68,1021.56,9006,683,713,4646.61,1641.25,196.13,706.73,4165.95,711.5,1407,2058,194.28,1491,220.57,6811,188.53,255.72,3433.18,32,4829.93,1738.89,737,316.8,2628,650,296,544,1192,4761,2701,1001,728,1890,743.16,504,336,280.61,20544.36,2248.05,309,358,644.08,514,459,3499,9936.33,18043.73,726,652.01,224.58,4199,1395.14,640,941.19,15433.1,785],
     [5.821811589,17.461879,6.162909108,19.27047488,53.25260753,4.877751357,10.40504949,3.779153242,3.805117811,8.307720954,14.60176991,7.741810661,7.636267212,5.254024329,7.598189159,7.198812145,317.832105,7.769548659,6.869135736,13.79492273,33.7658694,3.36616968,6.199540775,9.372977923,4.275038104,4.736626264,3.79269392,6.254716038,20.46570714,13.38582677,4.467214395,8.952011856,5.79310682,8.688659956,3.039799436,20.87872306,16.9164075,18.50283077,5.831477158,10.4373131,14.05364564,6.820552195,16.96216387,2.686224601,4.340917299,10.409776,67.70314255,8.306768085,11.79950163,12.87794924,2.937456322,4.304260887,7.096247961,34.14407436,7.380971693,9.372047075,0.476364887,7.2283678,11.77507492,4.140666998,14.48810601,135.1056875,1.626885837,8.052357199,0.011915866,22.54141737,10.94267422,18.2329938,10.91709409,7.165270156,6.933099961,5.943367882,41.05773224,6.504278039,28.27089625,12.61407992,2.199824447,8.562649443,10.88831279,7.148218464,5.761319099,12.34337838,7.278497921,6.410077691,4.247163243,6.04125824,0.072781859,18.04005922,6.331517989,13.50558915,44.46066186,6.226455327,11.08672033,0.946200812,9.502183406,3.726912372,17.85888443,6.293689999,8.531492372,148.2688391,6.986371401,4.617219827,16.73306773,1.759530792,0.698625703,100.7764121,5.463173489,5.965250965,4.157955865,5.179669588,4.872037915,11.92827443,6.495507537,4.629404614,14.54614565,8.003527726,65.6374893,11.2381591,5.636922581,17.09386839,3.075001201,26.30815416,11.57862018,4.013497623],
     [45,262,93,126,70,26,37,21,21,65,47,91,36,32,14,48,80,65,162,49,66,106,26,326,34,41,18,21,100,87,9,74,9,10,5,596,119,46,68,61,15,114,234,209,34,27,51,427,10,70,13,376,8,7,205,67,45,47,32,370,11,23,49,45,15,188,28,24,205,8,45,141,27,22,29,132,47,78,76,14,43,23,199,51,15,107,16,158,16,41,18,28,18,18,21,30,108,63,30,25,205,12,14,24,16,405,32,381,30,13,52,83,135,472,919,103,30,13,289,74,108,50,529,14],
     [81,375,106,169,81,49,41,28,42,94,129,251,49,126,20,78,85,103,252,65,104,309,193,474,221,71,36,91,180,117,22,113,52,26,12,820,142,66,244,115,38,168,331,346,96,37,71,1658,15,126,21,505,22,13,359,70,380,103,49,422,13,44,112,156,15,235,164,33,346,132,78,296,39,68,29,204,119,83,101,14,52,30,737,124,17,173,65,182,60,129,22,210,23,54,29,60,169,141,45,28,226,24,29,43,27,507,138,416,69,64,73,83,190,1714,2185,217,48,15,409,79,278,58,1576,118]]
print(b)

[[656.96, 7100, 3021.76, 2240, 3647.99, 152, 1584.2, 4780, 2012.98, 2909, 1056, 5682.04, 5915.09, 1865, 621, 1406, 3889.82, 652.2, 1283, 2293.09, 4814, 5798.37, 2511, 14862, 1739, 2079, 530.12, 481.6, 1250.16, 731, 1430, 1487.11, 568.74, 220.97, 194, 14095.37, 1795, 574.87, 2339.23, 3743, 372, 3842, 9139.66, 9878, 1202, 1336.66, 4599, 17750.02, 1216, 5686.31, 508.6, 5855, 696, 2204, 910, 1091, 665, 1225.59, 668, 12170, 126.5, 1798, 1445, 2147, 681.14, 2687.78, 951.68, 1021.56, 9006, 683, 713, 4646.61, 1641.25, 196.13, 706.73, 4165.95, 711.5, 1407, 2058, 194.28, 1491, 220.57, 6811, 188.53, 255.72, 3433.18, 32, 4829.93, 1738.89, 737, 316.8, 2628, 650, 296, 544, 1192, 4761, 2701, 1001, 728, 1890, 743.16, 504, 336, 280.61, 20544.36, 2248.05, 309, 358, 644.08, 514, 459, 3499, 9936.33, 18043.73, 726, 652.01, 224.58, 4199, 1395.14, 640, 941.19, 15433.1, 785], [5.821811589, 17.461879, 6.162909108, 19.27047488, 53.25260753, 4.877751357, 10.40504949, 3.779153242, 3.805117811, 8.307720954, 14.60176991, 7.741810661, 7.636267212, 5.254024329, 7.598189159, 7.198812145, 317.832105, 7.769548659, 6.869135736, 13.79492273, 33.7658694, 3.36616968, 6.199540775, 9.372977923, 4.275038104, 4.736626264, 3.79269392, 6.254716038, 20.46570714, 13.38582677, 4.467214395, 8.952011856, 5.79310682, 8.688659956, 3.039799436, 20.87872306, 16.9164075, 18.50283077, 5.831477158, 10.4373131, 14.05364564, 6.820552195, 16.96216387, 2.686224601, 4.340917299, 10.409776, 67.70314255, 8.306768085, 11.79950163, 12.87794924, 2.937456322, 4.304260887, 7.096247961, 34.14407436, 7.380971693, 9.372047075, 0.476364887, 7.2283678, 11.77507492, 4.140666998, 14.48810601, 135.1056875, 1.626885837, 8.052357199, 0.011915866, 22.54141737, 10.94267422, 18.2329938, 10.91709409, 7.165270156, 6.933099961, 5.943367882, 41.05773224, 6.504278039, 28.27089625, 12.61407992, 2.199824447, 8.562649443, 10.88831279, 7.148218464, 5.761319099, 12.34337838, 7.278497921, 6.410077691, 4.247163243, 6.04125824, 0.072781859, 18.04005922, 6.331517989, 13.50558915, 44.46066186, 6.226455327, 11.08672033, 0.946200812, 9.502183406, 3.726912372, 17.85888443, 6.293689999, 8.531492372, 148.2688391, 6.986371401, 4.617219827, 16.73306773, 1.759530792, 0.698625703, 100.7764121, 5.463173489, 5.965250965, 4.157955865, 5.179669588, 4.872037915, 11.92827443, 6.495507537, 4.629404614, 14.54614565, 8.003527726, 65.6374893, 11.2381591, 5.636922581, 17.09386839, 3.075001201, 26.30815416, 11.57862018, 4.013497623], [45, 262, 93, 126, 70, 26, 37, 21, 21, 65, 47, 91, 36, 32, 14, 48, 80, 65, 162, 49, 66, 106, 26, 326, 34, 41, 18, 21, 100, 87, 9, 74, 9, 10, 5, 596, 119, 46, 68, 61, 15, 114, 234, 209, 34, 27, 51, 427, 10, 70, 13, 376, 8, 7, 205, 67, 45, 47, 32, 370, 11, 23, 49, 45, 15, 188, 28, 24, 205, 8, 45, 141, 27, 22, 29, 132, 47, 78, 76, 14, 43, 23, 199, 51, 15, 107, 16, 158, 16, 41, 18, 28, 18, 18, 21, 30, 108, 63, 30, 25, 205, 12, 14, 24, 16, 405, 32, 381, 30, 13, 52, 83, 135, 472, 919, 103, 30, 13, 289, 74, 108, 50, 529, 14], [81, 375, 106, 169, 81, 49, 41, 28, 42, 94, 129, 251, 49, 126, 20, 78, 85, 103, 252, 65, 104, 309, 193, 474, 221, 71, 36, 91, 180, 117, 22, 113, 52, 26, 12, 820, 142, 66, 244, 115, 38, 168, 331, 346, 96, 37, 71, 1658, 15, 126, 21, 505, 22, 13, 359, 70, 380, 103, 49, 422, 13, 44, 112, 156, 15, 235, 164, 33, 346, 132, 78, 296, 39, 68, 29, 204, 119, 83, 101, 14, 52, 30, 737, 124, 17, 173, 65, 182, 60, 129, 22, 210, 23, 54, 29, 60, 169, 141, 45, 28, 226, 24, 29, 43, 27, 507, 138, 416, 69, 64, 73, 83, 190, 1714, 2185, 217, 48, 15, 409, 79, 278, 58, 1576, 118]]